# Example cree configuration file

port = 80
root_directory = "./www"

enable_php = true
php_path = "C:\\php\\php-cgi.exe"


use_compression = true

[headers]
content_security_policy = "default-src 'self'"

